sonar.projectKey=ibernabelda-arch_Algoritmo-Minimax-y-Poda-Alfa-Beta
sonar.organization=ibernelda-arch
sonar.projectName=Algoritmo-Minimax-y-Poda-Alfa-Beta
sonar.sources=src
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8